services:
    redis:
        image: redis:latest
        container_name: coreproject-tracker-redis
        networks:
            - tracker_network
        restart: always
        expose:
            - '6379' # Expose to other services in the network but not to localhost

    nginx:
        image: nginx:latest
        container_name: coreproject-tracker-nginx
        ports:
            - '12000:8000'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - tracker

        restart: always
        extra_hosts:
        - "host.docker.internal:host-gateway"

    tracker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: coreproject-tracker

        networks:
            - tracker_network
        depends_on:
            - redis
        restart: always
        environment:
            # Example environment variables
            REDIS_HOST: redis
            REDIS_PORT: 6379
            # This tells the tracker to lookup the real ip
            RUNNING_IN_DOCKER : True
        ports:
            - '8001:8000'
            - '9001:9000'
            - '8080:8080'
networks:
    tracker_network:
