services:
    redis:
        image: redis:latest
        container_name: redis
        networks:
            - app_network
        restart: always

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '12000:8000'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - app_network
        depends_on:
            - redis
        restart: always

    tracker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: coreproject-tracker

        networks:
            - app_network
        depends_on:
            - redis
        restart: always

networks:
    app_network:
        driver: bridge
