services:
    redis:
        image: redis:latest
        container_name: coreproject-tracker-redis
        networks:
            - tracker_network
        restart: always
        expose:
            - '6379' # Expose to other services in the network but not to localhost

    tracker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: coreproject-tracker

        networks:
            - tracker_network
        depends_on:
            - redis
        restart: always
        environment:
            # Example environment variables
            REDIS_HOST: redis
            REDIS_PORT: 6379
        ports:
            - '12000:8000/udp' #UDP
            - '12001:9000' # HTTP
            - '12002:8080' # Websocket
networks:
    tracker_network:
