services:
    redis:
        image: redis:latest
        container_name: coreproject-tracker-redis
        networks:
            - tracker_network
        restart: always
        expose:
            - '6379' # Expose to other services in the network but not to localhost

    traefik:
        image: traefik:latest
        command:
            - "--api.insecure=true"  # Enable dashboard
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:8000"
            - "--entrypoints.websecure.address=:8443"
            - "--entrypoints.udp.address=:8000/udp"  # UDP entrypoint
        ports:
            - "12000:8000"
            - "12000:8000/udp"  # UDP port
            - "8443:8443"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            
    tracker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: coreproject-tracker

        networks:
            - tracker_network
        depends_on:
            - redis
        restart: always
        environment:
            # Example environment variables
            REDIS_HOST: redis
            REDIS_PORT: 6379
            # This tells the tracker to lookup the real ip
            RUNNING_IN_DOCKER : True
        ports:
            - '8001:8000'
            - '9001:9000'
            - '8080:8080'

        labels:
            - "traefik.enable=true"
            
            # HTTP Configuration
            - "traefik.http.routers.tracker-http.entrypoints=web"
            - "traefik.http.routers.tracker-http.rule=PathPrefix(`/`)"
            - "traefik.http.services.tracker-http.loadbalancer.server.port=9000"
            
            # WebSocket Configuration
            - "traefik.http.routers.tracker-ws.entrypoints=web"
            - "traefik.http.routers.tracker-ws.rule=PathPrefix(`/`)"
            - "traefik.http.services.tracker-ws.loadbalancer.server.port=8080"
            - "traefik.http.middlewares.tracker-ws.headers.customrequestheaders.Connection=upgrade"
            - "traefik.http.middlewares.tracker-ws.headers.customrequestheaders.Upgrade=websocket"
            - "traefik.http.routers.tracker-ws.middlewares=tracker-ws"
            
            # UDP Configuration
            - "traefik.udp.routers.tracker-udp.entrypoints=udp"
            - "traefik.udp.services.tracker-udp.loadbalancer.server.port=8000"
networks:
    tracker_network:
