const x = {
    numwant: 10,
    uploaded: 0,
    downloaded: 0,
    left: 0,
    event: 'started',
    action: 1,
    
    info_hash: '0d41f01df552baa3e0c074bb87620b8287fd896e',
    peer_id: '2d5744303032342d4d384270616b772b78523534',
    offers: [
      { offer: [Object], offer_id: ' ¿ã`ÃdAËà\x9C¨G\x8DoÈ\x80\x01&6®' },
      { offer: [Object], offer_id: '\x9D}Z\x15\x83Lc×äï\f:CszººÎ}¤' },
      { offer: [Object], offer_id: "MÓÓÀ@¯X\x020ÕW\x8D~ëO\x12_1ý'" },
      {
        offer: [Object],
        offer_id: '\x89(^ã\x97 !ë¬õ\x12\x9F»:Ë\x15\x81\x82/²'
      },
      {
        offer: [Object],
        offer_id: '\x11\x9E^¬k\x1B\x1D\x8A\x84\x95Vê\x8C¶\x072gé\x02|'
      },
      {
        offer: [Object],
        offer_id: 'õ (\bfîº\x18v\x97©\b\x17"\x97EÊÞÉ\x80'
      },
      { offer: [Object], offer_id: 'LóÆ,SÌ¿gu\x04ÝõÍ4cð\x86\x11\x00E' },
      { offer: [Object], offer_id: 'µl\x01oX\r5À¢w»Ò\x85Àû\x7FHÍ\x802' },
      { offer: [Object], offer_id: ';kýÝ\x98Ð\x81Q°ÈK;¿!æ\x00\x15Õ*Ü' },
      { offer: [Object], offer_id: 'þÝÈ(E_JîFMí\x14·C÷í!<\x19ä' }
    ],
    type: 'ws',
    socket: <ref *1> WebSocket {
      _events: [Object: null prototype] {
        message: [Function (anonymous)],
        error: [Function (anonymous)],
        close: [Function (anonymous)]
      },
      _eventsCount: 3,
      _maxListeners: undefined,
      _binaryType: 'nodebuffer',
      _closeCode: 1006,
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: <Buffer >,
      _closeTimer: null,
      _errorEmitted: false,
      _extensions: {},
      _paused: false,
      _protocol: '',
      _readyState: 1,
      _receiver: Receiver {
        _events: [Object],
        _writableState: [WritableState],
        _maxListeners: undefined,
        _allowSynchronousEvents: true,
        _binaryType: 'nodebuffer',
        _extensions: {},
        _isServer: true,
        _maxPayload: 104857600,
        _skipUTF8Validation: false,
        _bufferedBytes: 0,
        _buffers: [],
        _compressed: false,
        _payloadLength: 11053,
        _mask: <Buffer 49 86 ca ce>,
        _fragmented: 0,
        _masked: true,
        _fin: true,
        _opcode: 1,
        _totalPayloadLength: 0,
        _messageLength: 0,
        _fragments: [],
        _errored: false,
        _loop: false,
        _state: 0,
        _eventsCount: 6,
        [Symbol(shapeMode)]: true,
        [Symbol(kCapture)]: false,
        [Symbol(websocket)]: [Circular *1]
      },
      _sender: Sender {
        _extensions: {},
        _socket: [Socket],
        _firstFragment: true,
        _compress: false,
        _bufferedBytes: 0,
        _queue: [],
        _state: 0,
        onerror: [Function: senderOnError],
        [Symbol(websocket)]: [Circular *1]
      },
      _socket: Socket {
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: null,
        _closeAfterHandlingError: false,
        _events: [Object],
        _readableState: [ReadableState],
        _writableState: [WritableState],
        allowHalfOpen: true,
        _maxListeners: undefined,
        _eventsCount: 4,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Server],
        _server: [Server],
        parser: null,
        on: [Function (anonymous)],
        addListener: [Function (anonymous)],
        prependListener: [Function: prependListener],
        setEncoding: [Function: socketSetEncoding],
        _paused: false,
        timeout: 0,
        _peername: [Object],
        [Symbol(async_id_symbol)]: 435,
        [Symbol(kHandle)]: [TCP],
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(shapeMode)]: true,
        [Symbol(kCapture)]: false,
        [Symbol(kSetNoDelay)]: true,
        [Symbol(kSetKeepAlive)]: false,
        [Symbol(kSetKeepAliveInitialDelay)]: 0,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(websocket)]: [Circular *1]
      },
      _autoPong: true,
      _isServer: true,
      upgradeReq: null,
      peerId: '2d5744303032342d4d384270616b772b78523534',
      infoHashes: [ '0d41f01df552baa3e0c074bb87620b8287fd896e' ],
      onSend: [Function (anonymous)],
      onMessageBound: [Function (anonymous)],
      onErrorBound: [Function (anonymous)],
      onCloseBound: [Function (anonymous)],
      ip: '127.0.0.1',
      port: 53226,
      addr: '127.0.0.1:53226',
      headers: {
        'sec-websocket-version': '13',
        'sec-websocket-key': 'fKooN21vBhpCjinTbcWV3w==',
        connection: 'Upgrade',
        upgrade: 'websocket',
        'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits',
        host: 'localhost:8000'
      },
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    compact: -1,
    ip: '127.0.0.1',
    port: 53226,
    addr: '127.0.0.1:53226',
    headers: {
      'sec-websocket-version': '13',
      'sec-websocket-key': 'fKooN21vBhpCjinTbcWV3w==',
      connection: 'Upgrade',
      upgrade: 'websocket',
      'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits',
      host: 'localhost:8000'
    }
  }