[project]
name = "coreproject-py-tracker"
version = "0.1.0"
description = ""
authors = [
    { name = "baseplate-admin", email = "61817579+baseplate-admin@users.noreply.github.com" },
]
requires-python = ">=3.13"
dependencies = [
    "twisted>=24.11.0",
    "autobahn[twisted]>=24.4.2,<25",
    "bencode-py>=4.0.0,<5",
    "redis[hiredis]>=5.2.1,<6",
    "packaging>=24.2",
]

[dependency-groups]
dev = ["poethepoet>=0.32.0,<0.33"]

[tool.uv]
package = false

[tool.hatch.build.targets.sdist]
include = ["./src/coreproject_tracker"]

[tool.hatch.build.targets.wheel]
include = ["./src/coreproject_tracker"]

[tool.hatch.build.targets.wheel.sources]
"./src/coreproject_tracker" = "coreproject_tracker"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.poe.tasks]
dev = "python ./src/run.py"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
ignore = ["E501", "C901"]
select = ["I", "E", "F", "W", "C"]
