"""Create a baseline migrations

Revision ID: 5c1d5042dc25
Revises: 
Create Date: 2025-01-08 02:56:19.761853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1d5042dc25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torrents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('info_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('info_hash')
    )
    op.create_table('peers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('is_seeding', sa.Boolean(), nullable=False),
    sa.Column('peer_id', sa.String(), nullable=False),
    sa.Column('torrent_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['torrent_id'], ['torrents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('torrent_id', 'ip', 'port', name='_peer_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peers')
    op.drop_table('torrents')
    # ### end Alembic commands ###
